### ISSUE TITLE
Split the R and Python Packages

### ISSUE THREAD

**Issue by jrnold** [virgesmith/UKCensusAPI#15]
Having the R and Python package share the same directory is confusing and could possibly lead to unforeseen release issues.

- Split into two repositories. This is clean, and usually people expect a packages to be in their own repository. Repositories are cheap (free)
- If they must be kept in the same repository, put the R and python packages in different directories.

This is part of the JOSS review openjournals/joss-reviews#408

**Comment by jrnold** [comment]
Combining the tests for both R and python in the same directory: https://github.com/virgesmith/UKCensusAPI/tree/master/tests is not ideal since under some configurations R will install the unrelated python tests.

**Comment by virgesmith** [comment]
I'm loath to split the packages, as the idea of having a single package that works in both R and python was a key driver to creating this package. If split they will inevitably diverge, and the R package will have a dependency on a separate non-R package which will complicate installation.

I appreciate some compromises have to be made due to package structure restrictions - the scripts need be be under the `inst` directory or R won't install them, and the test directory (as you point out) contains both R and python scripts, but on balance I don't see this as a major issue - unless there's something I haven't thought of?
